config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :articles

  root 'articles#homepage'

  get 'signup', to: 'users#new'
  
  # post 'users', to: 'users#create'
  resources :users, except:[:new]

  get 'login', to: "sessions#new"
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :user
    validates :title, presence: true, length:{minimum:3,maximum:50}

    validates :user_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord

    has_many :articles
    before_save {self.email = email.downcase}

    validates :username, presence: true, 
        uniqueness:{case_sensetive:false},
        length:{minimum: 3, maximum:25}

    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
    validates :email, presence: true, 
        uniqueness:{case_sensetive:false},
        length: {maximum: 100},
        format: {with: VALID_EMAIL_REGEX }
    
    has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method :current_user, :logged_in?

    def current_user

        @current_user ||= User.find(session[:user_id]) if session[:user_id]

    end

    def logged_in?

        !!current_user

    end

    def require_user
        if !logged_in
            flash[:danger] = "You must be logged in to perform that action"
            redirect_to root_path
        end

    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

    def homepage
    end

    def index

        @articles = Article.all

    end
    
    def new
        @article = Article.new
    end

    def edit

        @article = Article.find(params[:id])

    end

    def create
            # render plain: params[:article].inspect
            @article = Article.new(article_params)
            @article.user = User.first

            if @article.save
                flash[:notice] = "Article was successfully created"

                redirect_to article_path(@article)
            else
                render 'new'
            end 
            # @article.save
            # redirect_to article_path(@article)
    end

    def update
        @article = Article.find(params[:id])
        if @article.update(article_params)
          flash[:notice] = "Articlce was successfully updated"
          redirect_to article_path(@article)
        else
            render 'edit'
        end

    end

    def show

        @article = Article.find(params[:id])
    end

    def destroy
        @article = Article.find(params[:id])
        @article.destroy
        flash[:notice] = "Article was deleted"
        redirect_to articles_path
    end

    private
        def article_params
            params.require(:article).permit(:title, :descritption)
        end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new

    end

    def create
        user = User.find_by(email: params[:session][:email].downcase)
        if user && user.authenticate(params[:session][:password])
            session[:user_id] = user.id
            flash[:success] = "You have successfully logged in"
            redirect_to user_path(user)

        else
            flash.now[:danger] = "There was something wrong with your login information"
            render 'new'
        end

    end

    def destroy
        session[:user_id] = nil
        flash[:success]  = "You have logged out"
        redirect_to root_path

        
    end
end

app/controllers/users_controller.rb
class UsersController <ApplicationController
    
    def index
        @users = User.all
    end
    
    def new

        @user = User.new

    end

    def create
        @user = User.new(user_params)
        if @user.save

            session[:user_id] = @user_id
            flash[:success] = "Welcome #{@user.username}"
            redirect_to articles_path
        else
            render 'new'
        end

    end

    def edit
        @user = User.find(params[:id])

    end

    def update
        @user = User.find(params[:id])
        if @user.update(user_params)

            flash[:success] = "Your account was updated successfully"
            redirect_to articles_path
        
        else
            render 'edit'
        end

    end

    def show
        @user = User.find(params[:id])
    end

    private 
    def user_params
        params.require(:user).permit(:username, :email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def gravatar_for(user)
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
        image_tag(gravatar_url, alt:user.username, class: "img-circle")
    end
end

app/views/articles/_article.html.erb
<p>
    <%= link_to "Create new article", new_article_path%>
</p>

<table>
    <tr>
        <th>Title</th>
        <th>Description</th>
    </tr>

    <% obj.each do |article|%>
    <tr>
       
    <td> <%= article.title%> </td>
        
    <td><%= article.descritption%> </td>

    <td> <%= link_to "Edit", edit_article_path(article)%> </td>
    <td> <%= link_to "Show", article_path(article) %> </td>
    <td> <%= link_to "Delete", article_path(article), method: :delete, data:{confirm: "Are you sure?"}%> </td>
    <td><small> (Created by): <%= article.user.username if article.user%> </small> </td>
            
    </tr>
    <%end%>
</table>

app/views/articles/_form.html.erb
<% if @article.errors.any? %>
<ul>
  <% @article.errors.full_messages.each do |msg| %>
    <li>
      <%= msg %>
    </li>

  <%end%>
</ul>

<%end%>

<%= form_for @article do |f| %>
    <p>
        <%= f.label :title %> <br>
        <%= f.text_field :title %>
        
    </p>
    <p>
        <%= f.label :descritption %> <br>
        <%= f.text_area :descritption %>
    </p>
    <p>
        <%= f.submit %> 
    </p>

<% end %>

<%= link_to "Go back to articles listing", articles_path%>

app/views/articles/edit.html.erb
<h1> Edit existing Article </h1>

<% if @article.errors.any? %>
<ul>
  <% @article.errors.full_messages.each do |msg| %>
    <li>
      <%= msg %>
    </li>

  <%end%>
</ul>

<%end%>

<%= form_for @article do |f| %>
    <p>
        <%= f.label :title %> <br>
        <%= f.text_field :title %>
        
    </p>
    <p>
        <%= f.label :descritption %> <br>
        <%= f.text_area :descritption %>
    </p>
    <p>
        <%= f.submit %> 
    </p>

<% end %>

<%= link_to "Go back to articles listing", articles_path%>

app/views/articles/homepage.html.erb
<div class="center jumbotron">
  <h1>My Articles</h1>
  <%= link_to "Sign up now", signup_path , class: "btn btn-primary btn-lg" %>

  </div>

app/views/articles/index.html.erb
<h1> Listing all articles </h1>

<%= render 'article', obj: @articles %> 

app/views/articles/new.html.erb
<h1> Create a new Article </h1>

<% if @article.errors.any? %>
<ul>
  <% @article.errors.full_messages.each do |msg| %>
    <li>
      <%= msg %>
    </li>

  <%end%>
</ul>

<%end%>

<%= form_for @article do |f| %>
    <p>
        <%= f.label :title %> <br>
        <%= f.text_field :title %>
        
    </p>
    <p>
        <%= f.label :descritption %> <br>
        <%= f.text_area :descritption %>
    </p>
    <p>
        <%= f.submit %> 
    </p>

<% end %>

app/views/articles/show.html.erb
<h1> Showing selected article </h1>
<ul class = "listing">
    <div class ="row">
        <div class = "well col-md-4 col-md-offset-4">
            <li><%= link_to gravatar_for(@article.user), user_path(@article.user)%></li>
            <li class = "article-title">
                <%=link_to @article.username, user_path(@article.user)%>
            </li>
            <li><small><%= pluralize(@article.user.articles.count, "article") if @article.user.articles%></small></li>
        </div>
    </div>
</ul>

<p>
    Title: <%= @article.title %>
</p>

<p>
    Description: <%= @article.descritption %>
</p>

<%= link_to "Edit this article", edit_article_path%> |
<%= link_to "Go back to articles listing", articles_path%>


app/views/layouts/_footer.html.erb
<div class = 'container'>
    <footer class = 'footer'>
        <small>
            Copyright &copy; <a href ="https:/www.google.com"> GOOGLE </a>
            by Jodat
        </small>

        <nav>
            <ul>
                <li><%= link_to "Show Articles", articles_path %> </li>
            </ul>
        </nav>
    </footer>
</div> 

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg bg-info">
  <div class="container-fluid">
    
    <%= link_to "My Articles", root_path, class: "navbar-brand", id: "logo" %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Articles", articles_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            
            <li><%= link_to "New Article", new_article_path %></li>
            
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <%= link_to "Log out", logout_path, method: :delete, class: "nav-link"%>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsUi</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>

  <%= render 'layouts/navigation' %>

  <div class="container">


  <% flash.each do |name,msg| %>
    <ul>
      <li>
        <%= msg%>
        </li>
      </ul>
  
  <%end%>

    <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
    <br>
    <br>
    <br>
    <br>
    <br>
    <%= debug(params) if Rails.env.development? %>
    
  </body>
</html>

app/views/users/_form.html.erb


<% if @user.errors.any? %>
<ul>
  <% @user.errors.full_messages.each do |msg| %>
    <li>
      <%= msg %>
    </li>

  <%end%>
</ul>

<%end%>

<%= form_for @user do |f| %>
    <p>
        <%= f.label :username %> <br>
        <%= f.text_field :username, placeholder:"Enter username" %>
        
    </p>
    <p>
        <%= f.label :email %> <br>
        <%= f.email_field :email, placeholder:"Enter email" %>
    </p>
    <p>
        <%= f.label :passwrod  %> <br>
        <%= f.password_field :password, placeholder:"Enter password" %>
    </p>
    <p>
        <%= f.submit(@user.new_record? ? "Sign up" : "Update your account") %> 
    </p>

<% end %>

<%= link_to "Go back to articles listing", articles_path%>  

app/views/users/edit.html.erb
<h1> Edit your account </h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1> All Users </h1>

<% @users.each do |user| %>
    <ul class = "listing">
        <div class ="row">
            <div class = "well col-md-4 col-md-offset-4">
                <li><%= link_to gravatar_for(user), user_path(user)%></li>
                <li class = "article-title">
                    <%=link_to user.username, user_path(user)%>
                </li>
                <li><small><%= pluralize(user.articles.count, "article") if user.articles%></small></li>
            </div>
        </div>
    </ul>
<%end%>

app/views/users/new.html.erb
<h1 align='center'>  Sign up  </h1>

<%= render 'form' %> 

app/views/users/show.html.erb
<h1> Welcome to <%= @user.username %> 's page </h1>

<div class = "row">
    <div class "col-md-4 col-md-offset-4 center">
        <%= gravatar_for @user %>
    </div>
</div>
<h4><%= @user.username %> 's articles </h4>

<%= render 'articles/article', obj: @user.articles %>  